# Generated by Django 3.0.2 on 2020-01-06 20:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('balance', models.IntegerField(default=0)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('object', models.CharField(choices=[('Food', 'Food'), ('Education', 'Education'), ('Shopping', 'Shopping'), ('Personal Care', 'Personal Care'), ('Health & Fitness', 'Health & Fitness'), ('Kids', 'Kids'), ('Food & Dining', 'Food & Dining'), ('Gifts & Donations', 'Gifts & Donations'), ('Auto & Transport', 'Auto & Transport'), ('Travel', 'Travel'), ('Fees & Charges', 'Fees & Charges'), ('Taxes', 'Taxes'), ('Investments', 'Investments')], max_length=30)),
                ('comment', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Debit', 'Debit'), ('Credit', 'Credit')], max_length=30)),
                ('transaction_date', models.DateField(verbose_name=datetime.datetime(2020, 1, 6, 22, 52, 22, 689365))),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Account')),
            ],
        ),
    ]
