# Generated by Django 3.0.2 on 2020-01-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200107_1138'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='balance_start',
            field=models.IntegerField(default=0),
        ),
    ]
