# Generated by Django 3.0.2 on 2020-01-07 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_account_balance_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='date_creation',
            field=models.DateField(null=True),
        ),
    ]
