# Generated by Django 3.0.2 on 2020-01-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_auto_20200115_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='currency',
            field=models.CharField(choices=[('₪', '₪'), ('$', '$'), ('€', '€')], max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('₪', '₪'), ('$', '$'), ('€', '€')], max_length=30),
        ),
    ]
